version: 2.1

orbs:
  clair: ovotech/clair-scanner@dev:clair-reports

jobs:
  scan_images:
    executor: clair/default
    steps:
    - run: |
        echo "debian:stretch" > /images.txt
        echo "debian:sid" >> /images.txt
    - clair/scan:
        image_file: /images.txt

  scan_image:
    executor: clair/default
    steps:
    - clair/scan:
        image: debian:jessie

workflows:
  test:
    jobs:
    - scan_images
    - scan_image
